DROP TABLE doc_entity IF EXISTS;
DROP TABLE products_in_store IF EXISTS;
DROP TABLE store IF EXISTS;
DROP TABLE product IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS BIGINT START WITH 100000;

CREATE TABLE product
(
    id            BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    purchasePrice FLOAT   NOT NULL,
    sellingPrice  FLOAT   NOT NULL
);

CREATE TABLE store
(
    id   BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE products_in_store
(
    store_id         BIGINT  NOT NULL,
    product_id       BIGINT  NOT NULL,
    product_quantity INTEGER NOT NULL,
    FOREIGN KEY (store_id) REFERENCES store (id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE TABLE doc_entity
(
    id                 BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    type               VARCHAR(35),
    enter_store_id     BIGINT,
    write_off_store_id BIGINT,
    products VARCHAR(1000) NOT NULL
);